### ISSUE TITLE
Potential enhancements?

### ISSUE THREAD

**Issue by cjm23** [USDAForestService/ForestVegetationSimulator-Utilities#26]
Hi, I have suggestions for two potential enhancements: 1) would it be possible to report on the age of the dominant cohort in the stand in it's own column? 2) would it be possible to export metrics (e.g., diameter, basal area, height) about second most present cohort in the stand?  For 1, I think age might be of interest to help determine "old forests".  And for 2, I'm working with R2's proposed new PIPO HSS and they want to know the size class associated with the secondary layer in a stand as they have a main size class based on QMD and then split into different classes based on whether there is no secondary layer, a sapling secondary layer (2nd layer diameter > 1 & < 5), or a pole secondary layer  (diameter >5 & <9).  Thanks.

**Comment by cjm23** [comment]
Quick follow-up regarding 1, has the variable LSAGE replaced ST_AGE?  If so, ignore 1.

**Comment by markcastle1415** [comment]
Greetings,

First I want to apologize for the very long delay in getting back to you. Our staff did not receive a notification that an issue was posted to this repository (we primarily work out of an enterprise repository now and pull code from there into this public facing repository on a quarterly basis). We are working on adjusting the notification settings. Unfortunately, we can't calculate age of the dominant cohort as FVS does not derive tree age for every record. FVS will track age for trees that have an age specified in the input FVS_TreeInit table and for tree records produced by the establishment model. Currently, we don't have logic for determining Region 2 classifications. If it would be of interest to add Region 2 classifications, please reach out to me: mark.castle@usda.gov.
